version: '3.2'

networks:
    my-net:
        external: 
            name: my-net

services:

    peer1_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-55-153
        image: hyperledger/fabric-peer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        hostname: peer1.org2.midominio.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=my-net
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
            - CORE_PEER_ADDRESSAUTODETECT=true
            # - CORE_PEER_GOSSIP_ORGLEADER=false
            # - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_LOGGING_LEVEL=DEBUG
            - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
            - CORE_LOGGING_MSP=DEBUG
            # - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            # TLS settings
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org2.midominio.com:7052
            - CORE_PEER_ID=peer1.org2.midominio.com
            - CORE_PEER_ADDRESS=peer1.org2.midominio.com:8056
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.midominio.com:8056
            - CORE_PEER_LOCALMSPID=Org2MSP

            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1_org2:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb1234


        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/org2.midominio.com/peers/peer1.org2.midominio.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/org2.midominio.com/peers/peer1.org2.midominio.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/org2.midominio.com/users:/var/hyperledger/users
            - ../channel-artifacts/:/var/hyperledger/config
        ports:
            - 8056:7051
            - 8058:7053
        networks:
          my-net:
            aliases:
                - peer1.org2.midominio.com

    couchdb1_org2:
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER= couchdb
            - COUCHDB_PASSWORD=couchdb1234
        volumes:
            - ./couchdb1/:/opt/couchdb/data
        ports:
            - 5987:5984
        networks:
          my-net:
            aliases:
                - couchdb1.org2.midominio.com

