version: '3.3'
networks:
    my-net:
        external:
            name: my-net
services:
    zookeeper:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == hostname
        image: hyperledger/fabric-zookeeper
        hostname: zookeeper.midominio.com
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
            - ZOO_MY_ID=1
            - ZOO_SERVERS=server.1=zookeeper.midominio.com:2888:3888 server.2=zookeeper2.midominio.com:2888:3888 server.3=zookeeper3.midominio.com:2888:3888
        networks:
            my-net: 
                aliases:
                    - zookeeper.midominio.com

    zookeeper2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == hostname
        image: hyperledger/fabric-zookeeper
        hostname: zookeeper2.midominio.com
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
            - ZOO_MY_ID=2
            - ZOO_SERVERS=server.1=zookeeper.midominio.com:2888:3888 server.2=zookeeper2.midominio.com:2888:3888 server.3=zookeeper3.midominio.com:2888:3888
        networks:
            my-net: 
                aliases:
                    - zookeeper2.midominio.com
 
    zookeeper3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == hostname
        image: hyperledger/fabric-zookeeper
        hostname: zookeeper3.midominio.com
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
            - ZOO_MY_ID=3
            - ZOO_SERVERS=server.1=zookeeper.midominio.com:2888:3888 server.2=zookeeper2.midominio.com:2888:3888 server.3=zookeeper3.midominio.com:2888:3888
        networks:
            my-net: 
                aliases:
                    - zookeeper3.midominio.com