version: '3.3'
networks:
    my-net:
        external:
            name: my-net
services:
    kafka:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == hostname
        hostname: kafka.midominio.com
        image: hyperledger/fabric-kafka
        environment:
            - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
            - KAFKA_BROKER_ID=0
            - KAFKA_MIN_INSYNC_REPLICAS=2
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper.midominio.com:2181,zookeeper2.midominio.com:2181,zookeeper3.midominio.com:2181
            - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=36000
            - KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=36000
        networks:
            my-net: 
                aliases:
                    - kafka.midominio.com

    kafka2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == hostname
        hostname: kafka2.midominio.com
        image: hyperledger/fabric-kafka
        environment:
            - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
            - KAFKA_BROKER_ID=1
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA.MIN_INSYNC_REPLICAS=2
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper.midominio.com:2181,zookeeper2.midominio.com:2181,zookeeper3.midominio.com:2181
            - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=36000
            - KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=36000
        networks:
            my-net: 
                aliases:
                    - kafka2.midominio.com
                    
    kafka3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == hostname
        hostname: kafka3.midominio.com
        image: hyperledger/fabric-kafka
        environment:
            - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
            - KAFKA_BROKER_ID=2
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA.MIN_INSYNC_REPLICAS=2
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper.midominio.com:2181,zookeeper2.midominio.com:2181,zookeeper3.midominio.com:2181
            - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=36000
            - KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=36000
        networks:
            my-net: 
                aliases:
                    - kafka3.midominio.com

    kafka4:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == hostname
        hostname: kafka4.midominio.com
        image: hyperledger/fabric-kafka
        environment:
            - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
            - KAFKA_BROKER_ID=3
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA.MIN_INSYNC_REPLICAS=2
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper.midominio.com:2181,zookeeper2.midominio.com:2181,zookeeper3.midominio.com:2181
            - KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS=36000
            - KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS=36000
        networks:
                my-net: 
                    aliases:
                        - kafka4.midominio.com