# Copyright Business Blockchain www.blockchainempresarial.com. All Rights Reserved.
# Autor: Ricardo Ruano, ricardo@business-blockchain.org
# Date: 16-11-2019
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  basic:


services:
  orderer.acme.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.acme.com
    container_name: orderer.acme.com
    networks:
      - basic

  peer0.org1.acme.com:
    container_name: peer0.org1.acme.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.acme.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    depends_on:
      - orderer.acme.com
      - couchdb0
    networks:
      - basic
  
  peer0.org2.acme.com:
    container_name: peer0.org2.acme.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.acme.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    depends_on:
      - orderer.acme.com
      - couchdb1
    networks:
      - basic

  peer0.org3.acme.com:
    container_name: peer0.org3.acme.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.acme.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
    depends_on:
      - orderer.acme.com
      - couchdb2
    networks:
      - basic

  couchdb0:
    image: hyperledger/fabric-couchdb
    ports:
      - 5984:5984
    container_name: couchdb0
    networks:
      - basic

  couchdb1:
    image: hyperledger/fabric-couchdb
    ports: 
      - 5985:5984
    container_name: couchdb1
    networks:
      - basic

  couchdb2:
    image: hyperledger/fabric-couchdb
    ports: 
      - 5986:5984
    container_name: couchdb2
    networks:
      - basic

  #CA for Org1
  ca.org1.acme.com:
    image: hyperledger/fabric-ca:1.4.1
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME:ca.org1.acme.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.acme.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/837da2ff9133209a766ad08d2658be810c98f0bd9a3abc626b61c5351b63c472_sk
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.acme.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/837da2ff9133209a766ad08d2658be810c98f0bd9a3abc626b61c5351b63c472_sk
    volumes:
      - ./crypto-config/peerOrganizations/org1.acme.com/ca/:/etc/hyperledger/fabric-ca-server-config
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    ports:
      - 7054:7054
    container_name: ca.org1.acme.com
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.acme.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.acme.com/peers/peer0.org1.acme.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.acme.com/peers/peer0.org1.acme.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.acme.com/peers/peer0.org1.acme.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.acme.com/users/Admin@org1.acme.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./../chaincode/:/opt/gopath/src/github.com/chaincode
      - /var/run/:/host/var/run/
    depends_on:
      - orderer.acme.com
      - peer0.org1.acme.com
      - peer0.org2.acme.com
      - peer0.org3.acme.com
    networks:
      - basic
